---

- name: cluster > CouchDB membership
  uri:
    url: "http://{{ inventory_hostname }}:5984/_membership"
    method: GET
    headers:
      Content-Type: "application/json"
    force_basic_auth: true
    user: "{{ couchdb_admin.user }}"
    password: "{{ couchdb_admin.pass | default( couchdb_admin.user ) }}"
    status_code: 200
  changed_when: false
  register: couchdb_membership

- name: cluster > Add node
  uri:
    url: "http://{{ inventory_hostname }}:5984/_cluster_setup"
    method: POST
    body_format: json
    body: "{{ lookup( 'template', 'add_node.json.j2' ) }}"
    headers:
      Content-Type: "application/json"
    force_basic_auth: true
    user: "{{ couchdb_admin.user }}"
    password: "{{ couchdb_admin.pass | default( couchdb_admin.user ) }}"
    status_code: [201, 409]
    changed_when: status_code == 201
  vars:
    couchdb_node_remote_host_name: "{{ couchdb_node_name_prefix }}@{{couchdb_node_remote_host }}"
  when:
    - couchdb_coordination_node is defined
    - couchdb_coordination_node == inventory_hostname
    - couchdb_node_remote_host_name not in couchdb_membership.json.all_nodes
  with_items: "{{ couchdb_cluster_nodes | difference( inventory_hostname ) }}"
  loop_control:
    loop_var: couchdb_node_remote_host

