---

- name: firewall > Stop iptables in CentOS 6
  service:
    name: iptables
    state: stopped
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: firewall > Stop firewalld in CentOS 7
  systemd:
    name: firewalld
    state: stopped
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

