---

- name: install > CouchDB packages
  yum:
    name: "{{ couchdb_packages }}"
    state: present
    update_cache: true

- name: install > CouchDB dependency on CentOS 6
  yum:
    name: libselinux-python
    state: present
    update_cache: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

