---

- name: yum > Apache CouchDB
  yum_repository:
    name: couchdb
    description: Apache-$releasever - CouchDB
    file: Apache-CouchDB
    baseurl: http://apache.bintray.com/couchdb-rpm/el$releasever/$basearch/
    enabled: yes
    gpgcheck: no
    repo_gpgcheck: no

- name: yum > EPEL
  yum:
    name: epel-release
    state: present
    update_cache: true

